# Generated by Django 4.1.3 on 2022-11-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "Inactive")],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="tag",
            field=models.ManyToManyField(null=True, to="inventory.tag"),
        ),
    ]
