# Generated by Django 4.1.3 on 2022-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_tag_item_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tag",
            field=models.ManyToManyField(to="inventory.tag"),
        ),
    ]
