# Generated by Django 4.1.3 on 2022-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_item_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "sku",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("price", models.IntegerField(null=True)),
                ("quantity", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(name="item",),
        migrations.DeleteModel(name="tag",),
    ]
