# Generated by Django 4.1.3 on 2022-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
