# Generated by Django 4.1.3 on 2022-12-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Card", "Card"), ("Cash", "Cash")],
                default="Cash",
                max_length=100,
                null=True,
            ),
        ),
    ]
