# Generated by Django 4.1.3 on 2022-12-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.BooleanField(default=False),
        ),
    ]
